// This file will be auto-generated by Supabase CLI
// For now, we'll define basic types that will be expanded later

export interface Database {
  public: {
    Enums: {
      user_role: 'admin' | 'moderator' | 'user';
    };
    Functions: {
      [_ in never]: never;
    };
    Tables: {
      // Permissions table
      permissions: {
        Insert: {
          created_at?: string;
          description?: null | string;
          id?: string;
          name: string;
        };
        Row: {
          created_at: string;
          description: null | string;
          id: string;
          name: string;
        };
        Update: {
          created_at?: string;
          description?: null | string;
          id?: string;
          name?: string;
        };
      };
      // User profiles table
      profiles: {
        Insert: {
          avatar_url?: null | string;
          company?: null | string;
          created_at?: string;
          department?: null | string;
          email?: null | string;
          full_name?: null | string;
          id: string;
          is_active?: boolean;
          job_title?: null | string;
          phone?: null | string;
          updated_at?: string;
          username?: null | string;
          website?: null | string;
        };
        Row: {
          avatar_url: null | string;
          company: null | string;
          created_at: string;
          department: null | string;
          email: null | string;
          full_name: null | string;
          id: string;
          is_active: boolean;
          job_title: null | string;
          phone: null | string;
          updated_at: string;
          username: null | string;
          website: null | string;
        };
        Update: {
          avatar_url?: null | string;
          company?: null | string;
          created_at?: string;
          department?: null | string;
          email?: null | string;
          full_name?: null | string;
          id?: string;
          is_active?: boolean;
          job_title?: null | string;
          phone?: null | string;
          updated_at?: string;
          username?: null | string;
          website?: null | string;
        };
      };
      // Role permissions table
      role_permissions: {
        Insert: {
          created_at?: string;
          id?: string;
          permission_id: string;
          role: string;
        };
        Row: {
          created_at: string;
          id: string;
          permission_id: string;
          role: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          permission_id?: string;
          role?: string;
        };
      };
      // User roles table
      user_roles: {
        Insert: {
          created_at?: string;
          id?: string;
          role: string;
          user_id: string;
        };
        Row: {
          created_at: string;
          id: string;
          role: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          role?: string;
          user_id?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
  };
}

// Helper types for easier usage
export type Profile = Database['public']['Tables']['profiles']['Row'];
export type UserRole = Database['public']['Tables']['user_roles']['Row'];
export type Permission = Database['public']['Tables']['permissions']['Row'];
export type RolePermission =
  Database['public']['Tables']['role_permissions']['Row'];

// Auth related types
export interface AuthUser {
  id: string;
  email: string;
  profile?: Profile;
  roles?: UserRole[];
  permissions?: string[];
}
